// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

//  ---------------------------------------------------------------------------
import Exchange from './abstract/korbit.js';
import { ExchangeError, AccountSuspended, BadRequest, AuthenticationError, InvalidOrder, InsufficientFunds, OrderNotFound, PermissionDenied, AddressPending, ArgumentsRequired, BadSymbol, InvalidAddress, DuplicateOrderId } from './base/errors.js';
import { Precise } from './base/Precise.js';
import { TICK_SIZE } from './base/functions/number.js';
import { sha512 } from './static_dependencies/noble-hashes/sha512.js';
import { sha256 } from './static_dependencies/noble-hashes/sha256.js';
import { jwt } from './base/functions/rsa.js';
//  ---------------------------------------------------------------------------
/**
 * @class korbit
 * @augments Exchange
 */
export default class korbit extends Exchange {
    describe() {
        return this.deepExtend(super.describe(), {
            'id': 'korbit',
            'name': 'Korbit',
            'countries': ['KR'],
            'version': 'v2',
            'rateLimit': 1000,
            'pro': true,
            // new metainfo interface
            'has': {
                'CORS': true,
                'spot': true,
                'margin': undefined,
                'swap': false,
                'future': false,
                'option': false,
                'cancelOrder': true,
                'createDepositAddress': true,
                'createMarketBuyOrderWithCost': true,
                'createMarketOrder': true,
                'createMarketOrderWithCost': false,
                'createMarketSellOrderWithCost': false,
                'createOrder': true,
                'fetchBalance': true,
                'fetchCanceledOrders': false,
                'fetchClosedOrders': false,
                'fetchCurrencies': true,
                'fetchDeposit': false,
                'fetchDepositAddress': true,
                'fetchDepositAddresses': true,
                'fetchDepositAddressesByNetwork': false,
                'fetchDeposits': true,
                'fetchFundingHistory': false,
                'fetchFundingRate': false,
                'fetchFundingRateHistory': false,
                'fetchFundingRates': false,
                'fetchIndexOHLCV': false,
                'fetchMarginMode': false,
                'fetchMarkets': true,
                'fetchMarkOHLCV': false,
                'fetchMyTrades': false,
                'fetchOHLCV': true,
                'fetchOpenInterestHistory': false,
                'fetchOpenOrders': true,
                'fetchOrder': true,
                'fetchOrderBook': true,
                'fetchOrderBooks': false,
                'fetchOrders': false,
                'fetchPositionMode': false,
                'fetchPremiumIndexOHLCV': false,
                'fetchTicker': true,
                'fetchTickers': true,
                'fetchTrades': true,
                'fetchTradingFee': true,
                'fetchTradingFees': true,
                'fetchTransactions': false,
                'fetchWithdrawal': false,
                'fetchWithdrawals': true,
                'transfer': false,
                'withdraw': true,
            },
            'timeframes': {
                '1m': '1',
                '5m': '5',
                '15m': '15',
                '30m': '30',
                '60m': '60',
                '240m': '240',
                '1d': '1D',
                '1w': '1W',
            },
            'hostname': 'api.korbit.co.kr',
            'urls': {
                'logo': 'https://user-images.githubusercontent.com/1294454/49245610-eeaabe00-f423-11e8-9cba-4b0aed794799.jpg',
                'api': {
                    'public': 'https://{hostname}',
                    'private': 'https://{hostname}',
                },
                'www': 'https://korbit.co.kr',
                'doc': 'https://docs.korbit.co.kr/',
                'fees': 'https://lightning.korbit.co.kr/events/fee-plan/',
            },
            'api': {
                'public': {
                    'get': {
                        'tickers': {'cost': 1 / 50, 'api_rate_limit_group': 'public'},
                        'orderbook': {'cost': 1 / 50, 'api_rate_limit_group': 'public'},
                        'trades': {'cost': 1 / 50, 'api_rate_limit_group': 'public'},
                        'candles': {'cost': 1 / 50, 'api_rate_limit_group': 'public'},
                        'currencyPairs': {'cost': 1 / 50, 'api_rate_limit_group': 'public'},
                        'currencies': {'cost': 1 / 50, 'api_rate_limit_group': 'public'},
                        'time': {'cost': 1 / 50, 'api_rate_limit_group': 'public'},
                    },
                },
                'private': {
                    'get': {
                        'orders': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'openOrders': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'allOrders': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'myTrades': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'balance': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/depositAddresses': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/depositAddress': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/recentDeposits': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/deposit': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/withdrawableAddresses': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/withdrawableAmount': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/recentWithdrawals': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/withdrawal': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'krw/recentDeposits': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'krw/recentWithdrawals': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'tradingFeePolicy': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'currentKeyInfo': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                    },
                    'post': {
                        'orders': {'cost': 1 / 30, 'api_rate_limit_group': 'order'},
                        'coin/depositAddress': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'coin/withdrawal': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                        'krw/sendKrwDepositPush': {'cost': 1 / 5, 'api_rate_limit_group': 'krwTransfer'},
                        'krw/sendKrwWithdrawalPush': {'cost': 1 / 5, 'api_rate_limit_group': 'krwTransfer'},
                    },
                    'delete': {
                        'orders': {'cost': 1 / 30, 'api_rate_limit_group': 'orderCancel'},
                        'coin/withdrawal': {'cost': 1 / 50, 'api_rate_limit_group': 'private'},
                    },
                },
            },
            'fees': {
                'trading': {
                    'tierBased': false,
                    'percentage': true,
                    'maker': this.parseNumber('0'),
                    'taker': this.parseNumber('0.2'),
                },
                'funding': {
                    'tierBased': false,
                    'percentage': false,
                    'withdraw': {},
                    'deposit': {},
                },
            },
            'precisionMode': TICK_SIZE,
            'exceptions': {
                'exact': {
                    'This key has expired.': AuthenticationError,
                    'Missing request parameter error. Check the required parameters!': BadRequest,
                    'side is missing, side does not have a valid value': InvalidOrder,
                },
                'broad': {
                    'DUPLICATE_CLIENT_ORDER_ID': DuplicateOrderId,
                    'INVALID_CURRENCY_PAIR': InvalidOrder,
                    'INVALID_USER_STATUS': AccountSuspended,
                    'BAD_REQUEST': BadRequest,
                    'NO_BALANCE': InsufficientFunds,
                    'ONLY_SELL_LIMIT_ORDERS_ALLOWED': BadRequest,
                    'ORDER_VALUE_TOO_LARGE': InvalidOrder,
                    'ORDER_VALUE_TOO_SMALL': InvalidOrder,
                    'PRICE_OVER_UPPER_BOUND': InvalidOrder,
                    'PRICE_UNDER_LOWER_BOUND': InvalidOrder,
                    'PRICE_TICK_SIZE_INVALID': InvalidOrder,
                    'TOO_MANY_OPEN_ORDERS': ExchangeError,
                    'ORDER_NOT_FOUND': OrderNotFound,
                    'ORDER_ALREADY_CANCELED': OrderNotFound,
                    'ORDER_ALREADY_FILLED': OrderNotFound,
                    'ORDER_ALREADY_EXPIRED': OrderNotFound,
                    'TRY_AGAIN': OrderNotFound,
                    'INVALID_CURRENCY': BadSymbol,
                    'WITHDRAWAL_SUSPENDED': InvalidAddress,
                    'UNREGISTERED_WITHDRAWAL_ADDRESS': InvalidAddress,
                    'FORBIDDEN_WITHDRAWAL_ADDRESS': InvalidAddress,
                    'WITHDRAWAL_ALREADY_IN_PROGRESS': ExchangeError,
                    'NO_BALANCE': InsufficientFunds,
                    'DAILY_LIMIT_EXCEEDED': ExchangeError,
                    'WITHDRAWAL_ALREADY_FINISHED': ExchangeError,
                    'CANNOT_CANCEL_WITHDRAWAL': ExchangeError,
                    'NOT_FOUND': ExchangeError,
                },
            },
            'options': {},
            'commonCurrencies': {},
        });
    }
    parseStatus(status) {
        const statuses = {
            'launched': true,
            'stopped': false,
        };
        return this.safeBool(statuses, status, false);
    }
    /**
     * @method
     * @name korbit#fetchMarkets
     * @see https://docs.korbit.co.kr/#REST-get-_v2_currencies
     * @description retrieves data on all currencies for korbit
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} an array of objects representing market data
     */
    async fetchCurrencies(params = {}) {
        const response = await this.publicGetCurrencies();
        // {
        //     "success": true,
        //     "data": [
        //         {
        //             "name": "krw",
        //             "fullName": "Won",
        //             "withdrawalMaxAmountPerRequest": "5000000000",
        //             "depositStatus": "launched",
        //             "withdrawalStatus": "launched",
        //             "withdrawalTxFee": "1000",
        //             "withdrawalMinAmount": "1000"
        //         },
        //         {
        //             "name": "btc",
        //             "fullName": "Bitcoin",
        //             "withdrawalMaxAmountPerRequest": "120",
        //             "defaultNetwork": "BTC",
        //             "networkList": [
        //                 {
        //                     "name": "BTC",
        //                     "fullName": "Bitcoin",
        //                     "depositStatus": "launched",
        //                     "withdrawalStatus": "launched",
        //                     "confirmationCount": 3,
        //                     "withdrawalTxFee": "0.0008",
        //                     "withdrawalMinAmount": "0.0001",
        //                     "withdrawalPrecision": 8,
        //                     "hasSecondaryAddr": false,
        //                     "addressExplorerUrl": "https://www.blockchain.com/ko/btc/address/"
        //                 }
        //             ],
        //             "depositStatus": "launched",
        //             "withdrawalStatus": "launched",
        //             "confirmationCount": "3",
        //             "withdrawalTxFee": "0.0008",
        //             "withdrawalMinAmount": "0.0001"
        //         },
        //         {
        //             "name": "eth",
        //             "fullName": "Ethereum",
        //             "withdrawalMaxAmountPerRequest": "2000",
        //             "defaultNetwork": "ETH",
        //             "networkList": [
        //                 {
        //                     "name": "ETH",
        //                     "fullName": "Ethereum",
        //                     "depositStatus": "launched",
        //                     "withdrawalStatus": "launched",
        //                     "confirmationCount": 45,
        //                     "withdrawalTxFee": "0.005",
        //                     "withdrawalMinAmount": "0.0001",
        //                     "withdrawalPrecision": 8,
        //                     "hasSecondaryAddr": false,
        //                     "addressExplorerUrl": "https://etherscan.io/address/"
        //                 },
        //                 {
        //                     "name": "BASE",
        //                     "fullName": "BASE",
        //                     "depositStatus": "launched",
        //                     "withdrawalStatus": "launched",
        //                     "confirmationCount": 1,
        //                     "withdrawalTxFee": "0.001",
        //                     "withdrawalMinAmount": "0.0001",
        //                     "withdrawalPrecision": 8,
        //                     "hasSecondaryAddr": false,
        //                     "addressExplorerUrl": "https://basescan.org/address/"
        //                 }
        //             ],
        //             "depositStatus": "launched",
        //             "withdrawalStatus": "launched",
        //             "confirmationCount": "45",
        //             "withdrawalTxFee": "0.005",
        //             "withdrawalMinAmount": "0.0001"
        //         },
        //         {
        //             "name": "usdt",
        //             "fullName": "Tether",
        //             "withdrawalMaxAmountPerRequest": "500000",
        //             "defaultNetwork": "TRX",
        //             "networkList": [
        //                 {
        //                     "name": "TRX",
        //                     "fullName": "Tron",
        //                     "depositStatus": "launched",
        //                     "withdrawalStatus": "launched",
        //                     "confirmationCount": 1,
        //                     "withdrawalTxFee": "1",
        //                     "withdrawalMinAmount": "1",
        //                     "withdrawalPrecision": 6,
        //                     "hasSecondaryAddr": false,
        //                     "addressExplorerUrl": "https://tronscan.org/#/address/"
        //                 }
        //             ],
        //             "depositStatus": "launched",
        //             "withdrawalStatus": "launched",
        //             "confirmationCount": "1",
        //             "withdrawalTxFee": "1",
        //             "withdrawalMinAmount": "1"
        //         }
        //     ]
        // }
        const data = this.safeValue(response, 'data', []);
        const result = {};
        for (let i = 0; i < data.length; i++) {
            const entry = data[i];
            const id = this.safeString(entry, 'name');
            const name = this.safeString(entry, 'fullName');
            const code = this.safeCurrencyCode(id);
            let minPrecision = undefined;
            let isWithdrawEnabled = false;
            let isDepositEnabled = false;
            const networkList = this.safeList(entry, 'networkList', []);
            const fees = {};
            let fee = undefined;
            const networks = {};
            for (let j = 0; j < networkList.length; j++) {
                const networkItem = networkList[j];
                const network = this.safeString(networkItem, 'name');
                const networkCode = this.networkIdToCode(network);
                // const name = this.safeString (networkItem, 'name');
                const withdrawFee = this.safeNumber(networkItem, 'withdrawalTxFee');
                const depositEnable = this.parseStatus(this.safeString(networkItem, 'depositStatus'));
                const withdrawEnable = this.parseStatus(this.safeString(networkItem, 'withdrawalStatus'));
                isDepositEnabled = isDepositEnabled || depositEnable;
                isWithdrawEnabled = isWithdrawEnabled || withdrawEnable;
                fees[network] = withdrawFee;
                const isDefault = j === 0;
                if (isDefault || (fee === undefined)) {
                    fee = withdrawFee;
                }
                const precisionDecimal = this.safeInteger(networkItem, 'withdrawalPrecision');
                const precisionTick = 10 ** -precisionDecimal
                minPrecision = (minPrecision === undefined) ? precisionTick : Math.min(minPrecision, precisionTick);
                networks[networkCode] = {
                    'info': networkItem,
                    'id': network,
                    'network': networkCode,
                    'active': depositEnable && withdrawEnable,
                    'deposit': depositEnable,
                    'withdraw': withdrawEnable,
                    'fee': withdrawFee,
                    'precision': this.parseNumber(precisionTick),
                    'limits': {
                        'withdraw': {
                            'min': this.safeNumber(networkItem, 'withdrawalMinAmount'),
                        }
                    },
                };
            }
            const active = isWithdrawEnabled && isDepositEnabled;
            result[code] = {
                'id': id,
                'name': name,
                'code': code,
                'precision': this.parseNumber(minPrecision),
                'info': entry,
                'active': active,
                'deposit': isDepositEnabled,
                'withdraw': isWithdrawEnabled,
                'networks': networks,
                'fee': fee,
                'fees': fees,
                'limits': this.limits,
            };
        }
        return result;
    }
    /**
     * @method
     * @name korbit#fetchMarkets
     * @see https://docs.korbit.co.kr/#REST-get-_v2_tradingFeePolicy
     * @description retrieves data on all markets for korbit
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} an array of objects representing market data
     */
    async fetchMarkets(params = {}) {
        const response = await this.privateGetTradingFeePolicy(params);
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "symbol": "btc_krw",
        //         "buyFeeCurrency": "btc",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       },
        //       {
        //         "symbol": "eth_krw",
        //         "buyFeeCurrency": "eth",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       },
        //       {
        //         "symbol": "etc_krw",
        //         "buyFeeCurrency": "krw",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       },
        //       {
        //         "symbol": "xrp_krw",
        //         "buyFeeCurrency": "krw",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       }
        //     ]
        // }
        const data = this.safeValue(response, 'data', []);
        const result = [];
        for (let i = 0; i < data.length; i++) {
            result.push(this.parseMarket(data[i]));
        }
        return result;
    }
    parseMarket(market) {
        //       {
        //         "symbol": "xrp_krw",
        //         "buyFeeCurrency": "krw",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       }
        const marketId = this.safeString(market, 'symbol');
        const [baseId, quoteId] = marketId.split('_');
        const base = this.safeCurrencyCode(baseId);
        const quote = this.safeCurrencyCode(quoteId);
        const makerFeeRate = this.safeNumber(market, 'makerFeeRate', this.fees['trading']['maker']);
        const takerFeeRate = this.safeNumber(market, 'takerFeeRate', this.fees['trading']['taker']);
        return this.safeMarketStructure({
            'id': marketId,
            'symbol': base + '/' + quote,
            'base': base,
            'quote': quote,
            'settle': undefined,
            'baseId': baseId,
            'quoteId': quoteId,
            'settleId': undefined,
            'type': 'spot',
            'spot': true,
            'margin': false,
            'swap': false,
            'future': false,
            'option': false,
            'active': true,
            'contract': false,
            'linear': undefined,
            'inverse': undefined,
            'taker': takerFeeRate,
            'maker': makerFeeRate,
            'contractSize': undefined,
            'expiry': undefined,
            'expiryDatetime': undefined,
            'strike': undefined,
            'optionType': undefined,
            'precision': {
                'price': this.parseNumber('1e-8'),
                'amount': this.parseNumber('1e-8'),
            },
            'limits': {
                'leverage': {
                    'min': undefined,
                    'max': undefined,
                },
                'amount': {
                    'min': undefined,
                    'max': undefined,
                },
                'price': {
                    'min': undefined,
                    'max': undefined,
                },
                'cost': {
                    'min': undefined,
                    'max': undefined,
                },
            },
            'created': undefined,
            'info': market,
        });
    }
    parseBalance(response) {
        // [
        //     {
        //         "currency": "btc",
        //         "balance": "100",
        //         "available": "70",
        //         "tradeInUse": "20",
        //         "withdrawalInUse": "10",
        //         "avgPrice": "5000"
        //     },
        //     {
        //         "currency": "eth",
        //         "balance": "100",
        //         "available": "70",
        //         "tradeInUse": "20",
        //         "withdrawalInUse": "10",
        //         "avgPrice": "5000"
        //     }
        // ]
        const result = {
            'info': response,
            'timestamp': undefined,
            'datetime': undefined,
        };
        for (let i = 0; i < response.length; i++) {
            const balance = response[i];
            const currencyId = this.safeString(balance, 'currency');
            const code = this.safeCurrencyCode(currencyId);
            const account = this.account();
            account['total'] = this.safeString(balance, 'balance');
            account['free'] = this.safeString(balance, 'available');
            result[code] = account;
        }
        return this.safeBalance(result);
    }
    /**
     * @method
     * @name korbit#fetchBalance
     * @see https://docs.korbit.co.kr/#REST-get-_v2_balance
     * @description query for balance and get the amount of funds available for trading or funds locked in orders
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
     */
    async fetchBalance(params = {}) {
        await this.loadMarkets();
        const response = await this.privateGetBalance(params);
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "currency": "btc",
        //         "balance": "100",
        //         "available": "70",
        //         "tradeInUse": "20",
        //         "withdrawalInUse": "10",
        //         "avgPrice": "5000"
        //       },
        //       {
        //         "currency": "eth",
        //         "balance": "100",
        //         "available": "70",
        //         "tradeInUse": "20",
        //         "withdrawalInUse": "10",
        //         "avgPrice": "5000"
        //       }
        //     ]
        // }
        const data = this.safeValue(response, 'data', []);
        return this.parseBalance(data);
    }
    /**
     * @method
     * @name korbit#fetchOrderBook
     * @see https://docs.korbit.co.kr/#REST-get-_v2_orderbook
     * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
     */
    async fetchOrderBook(symbol, limit = undefined, params = {}) {
        const marketId = this.marketId(symbol);
        const request = {
            'symbol': marketId,
        };
        const response = await this.publicGetOrderbook(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": {
        //       "timestamp": 1708057740895,
        //       "bids": [
        //         {
        //           "price": "73303000",
        //           "qty": "0.00898326"
        //         },
        //         {
        //           "price": "73302000",
        //           "qty": "0.00790837"
        //         },
        //         {
        //           "price": "73301000",
        //           "qty": "0.00843099"
        //         },
        //         {
        //           "price": "73300000",
        //           "qty": "0.00054024"
        //         },
        //         {
        //           "price": "73299000",
        //           "qty": "0.00663446"
        //         }
        //       ],
        //       "asks": [
        //         {
        //           "price": "73304000",
        //           "qty": "0.00985212"
        //         },
        //         {
        //           "price": "73305000",
        //           "qty": "0.00367505"
        //         },
        //         {
        //           "price": "73306000",
        //           "qty": "0.0096254"
        //         },
        //         {
        //           "price": "73307000",
        //           "qty": "0.00502544"
        //         },
        //         {
        //           "price": "73308000",
        //           "qty": "0.00640584"
        //         }
        //       ]
        //     }
        // }
        //
        const data = this.safeValue(response, 'data', {});
        const timestamp = this.safeInteger(data, 'timestamp');
        return {
            'symbol': symbol,
            'bids': this.sortBy(this.parseBidsAsks(data['bids'], 'price', 'qty'), 0, true),
            'asks': this.sortBy(this.parseBidsAsks(data['asks'], 'price', 'qty'), 0),
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'nonce': undefined,
        };
    }
    parseTicker(ticker, market = undefined) {
        //
        // {
        //     "symbol": "btc_krw",
        //     "open": "77060000",
        //     "high": "79650000",
        //     "low": "76550000",
        //     "close": "77136000",
        //     "prevClose": "77060000",
        //     "priceChange": "76000",
        //     "priceChangePercent": "0.1",
        //     "volume": "48.73739983",
        //     "quoteVolume": "3785149733.32633",
        //     "bestBidPrice": "77136000",
        //     "bestAskPrice": "77193000",
        //     "lastTradedAt": 1725525721041
        // }
        //
        const timestamp = this.safeInteger(ticker, 'lastTradedAt');
        const marketId = this.safeString(ticker, 'symbol');
        market = this.safeMarket(marketId, market, '_');
        const close = this.safeString(ticker, 'close');
        return this.safeTicker({
            'symbol': market['symbol'],
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'high': this.safeString(ticker, 'high'),
            'low': this.safeString(ticker, 'low'),
            'bid': undefined,
            'bidVolume': undefined,
            'ask': undefined,
            'askVolume': undefined,
            'vwap': undefined,
            'open': this.safeString(ticker, 'open'),
            'close': close,
            'last': close,
            'previousClose': this.safeString(ticker, 'prevClose'),
            'change': this.safeString(ticker, 'priceChange'),
            'percentage': this.safeString(ticker, 'priceChangePercent'),
            'average': undefined,
            'baseVolume': this.safeString(ticker, 'volume'),
            'quoteVolume': this.safeString(ticker, 'quoteVolume'),
            'info': ticker,
        }, market);
    }
    /**
     * @method
     * @name korbit#fetchTickers
     * @see https://docs.korbit.co.kr/#REST-get-_v2_tickers
     * @description fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
     * @param {string[]|undefined} symbols unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a dictionary of [ticker structures]{@link https://docs.ccxt.com/#/?id=ticker-structure}
     */
    async fetchTickers(symbols = undefined, params = {}) {
        await this.loadMarkets();
        symbols = this.marketSymbols(symbols);
        let ids = undefined;
        if (symbols === undefined) {
            ids = this.ids.join(',');
            // max URL length is 2083 symbols, including http schema, hostname, tld, etc...
            if (ids.length > this.options['fetchTickersMaxLength']) {
                const numIds = this.ids.length;
                throw new ExchangeError(this.id + ' fetchTickers() has ' + numIds.toString() + ' symbols exceeding max URL length, you are required to specify a list of symbols in the first argument to fetchTickers');
            }
        }
        else {
            ids = this.marketIds(symbols);
            ids = ids.join(',');
        }
        const request = {
            'symbol': ids,
        };
        const response = await this.publicGetTickers(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "symbol": "btc_krw",
        //         "open": "77060000",
        //         "high": "79650000",
        //         "low": "76550000",
        //         "close": "77136000",
        //         "prevClose": "77060000",
        //         "priceChange": "76000",
        //         "priceChangePercent": "0.1",
        //         "volume": "48.73739983",
        //         "quoteVolume": "3785149733.32633",
        //         "bestBidPrice": "77136000",
        //         "bestAskPrice": "77193000",
        //         "lastTradedAt": 1725525721041
        //       },
        //       {
        //         "symbol": "eth_krw",
        //         "open": "3259000",
        //         "high": "3370000",
        //         "low": "3222000",
        //         "close": "3250000",
        //         "prevClose": "3259000",
        //         "priceChange": "-9000",
        //         "priceChangePercent": "-0.28",
        //         "volume": "161.99278306",
        //         "quoteVolume": "532827941.01581",
        //         "bestBidPrice": "3251000",
        //         "bestAskPrice": "3254000",
        //         "lastTradedAt": 1725525545630
        //       }
        //     ]
        // }
        //
        const data = this.safeValue(response, 'data', []);
        const result = {};
        for (let t = 0; t < data.length; t++) {
            const ticker = this.parseTicker(data[t]);
            const symbol = this.symbol(ticker['symbol']);
            result[symbol] = ticker;
        }
        return this.filterByArrayTickers(result, 'symbol', symbols);
    }
    /**
     * @method
     * @name korbit#fetchTicker
     * @see https://docs.korbit.com/reference/ticker%ED%98%84%EC%9E%AC%EA%B0%80-%EC%A0%95%EB%B3%B4
     * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
     */
    async fetchTicker(symbol, params = {}) {
        const tickers = await this.fetchTickers([symbol], params);
        return this.safeValue(tickers, symbol);
    }
    parseTrade(trade, market = undefined) {
        //
        // fetchTrades
        //
        // {
        //     "timestamp": 1708057270922,
        //     "price": "70509000",
        //     "qty": "0.00844147",
        //     "isBuyerTaker": false,
        //     "tradeId": 21769250,
        // }
        //
        // fetchMyTrades
        //
        // {
        //     "symbol": "btc_krw",
        //     "tradeId": 52,
        //     "orderId": 382312,
        //     "side": "buy",
        //     "price": "5000",
        //     "qty": "10",
        //     "amt": "50000",
        //     "tradedAt": 1700000000000,
        //     "isTaker": true,
        //     "feeCurrency": "krw",
        //     "feeQty": "50"
        // }
        //
        const id = this.safeString(trade, 'tradeId');
        const orderId = this.safeString(trade, 'orderId');
        const timestamp = this.safeInteger2(trade, 'timestamp', 'tradedAt');
        const side = this.safeString(trade, 'side');
        if (side !== undefined) {
            const isBuyerTaker = this.safeString(trade, 'isBuyerTaker');
            if (isBuyerTaker === true) {
                side = 'sell';
            }
            else {
                side = 'buy';
            }
        }
        const price = this.safeString(trade, 'price');
        const amount = this.safeString(trade, 'qty');
        const marketId = this.safeString(trade, 'symbol');
        market = this.safeMarket(marketId, market, '_');
        let fee = undefined;
        const feeCost = this.safeString(trade, 'feeQty');
        if (feeCost !== undefined) {
            fee = {
                'currency': market['quote'],
                'cost': feeCost,
            };
        }
        const isTaker = this.safeString(trade, 'isTaker');
        let takerOrMaker = undefined;
        if (isTaker !== undefined) {
            takerOrMaker = isTaker ? 'taker' : 'maker'
        }
        return this.safeTrade({
            'id': id,
            'info': trade,
            'order': orderId,
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'symbol': market['symbol'],
            'type': undefined,
            'side': side,
            'takerOrMaker': takerOrMaker,
            'price': price,
            'amount': amount,
            'cost': cost,
            'fee': fee,
        }, market);
    }
    /**
     * @method
     * @name korbit#fetchTrades
     * @see https://docs.korbit.co.kr/#REST-get-_v2_trades
     * @description get the list of most recent trades for a particular symbol
     * @param {string} symbol unified symbol of the market to fetch trades for
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum amount of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=public-trades}
     */
    async fetchTrades(symbol, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        if (limit === undefined) {
            limit = 200;
        }
        const request = {
            'market': market['id'],
            'count': limit,
        };
        const response = await this.publicGetTrades(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "timestamp": 1708057271149,
        //         "price": "70507000",
        //         "qty": "0.00981535",
        //         "isBuyerTaker": false
        //       },
        //       {
        //         "timestamp": 1708057271035,
        //         "price": "70508000",
        //         "qty": "0.00682475",
        //         "isBuyerTaker": false
        //       },
        //       {
        //         "timestamp": 1708057270922,
        //         "price": "70509000",
        //         "qty": "0.00844147",
        //         "isBuyerTaker": false
        //       },
        //       {
        //         "timestamp": 1708057270809,
        //         "price": "70510000",
        //         "qty": "0.00553963",
        //         "isBuyerTaker": false
        //       }
        //     ]
        // }
        //
        const data = this.safeValue(response, 'data', []);
        for (let i = 0; i < data.length; i++) {
            const entry = data[i];
            entry['symbol'] = market['id'];
        }
        return this.parseTrades(response, market, since, limit);
    }
    /**
     * @method
     * @name korbit#fetchTradingFees
     * @see https://docs.korbit.co.kr/#REST-get-_v2_tradingFeePolicy
     * @description fetch the trading fees for a market
     * @param {string[]|undefined} symbols unified symbols of the markets
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [fee structure]{@link https://docs.ccxt.com/#/?id=fee-structure}
     */
    async fetchTradingFees(symbols, params = {}) {
        await this.loadMarkets();
        symbols = this.marketSymbols(symbols);
        let ids = undefined;
        if (symbols === undefined) {
            ids = this.ids.join(',');
            // max URL length is 2083 symbols, including http schema, hostname, tld, etc...
            if (ids.length > this.options['fetchTickersMaxLength']) {
                const numIds = this.ids.length;
                throw new ExchangeError(this.id + ' fetchTickers() has ' + numIds.toString() + ' symbols exceeding max URL length, you are required to specify a list of symbols in the first argument to fetchTickers');
            }
        }
        else {
            ids = this.marketIds(symbols);
            ids = ids.join(',');
        }
        const request = {
            'symbol': ids,
        };
        const response = await this.privateGetTradingFeePolicy(this.extend(request, params));
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "symbol": "btc_krw",
        //         "buyFeeCurrency": "btc",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       },
        //       {
        //         "symbol": "eth_krw",
        //         "buyFeeCurrency": "eth",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       },
        //       {
        //         "symbol": "etc_krw",
        //         "buyFeeCurrency": "krw",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       },
        //       {
        //         "symbol": "xrp_krw",
        //         "buyFeeCurrency": "krw",
        //         "sellFeeCurrency": "krw",
        //         "maxFeeRate": "0.0015",
        //         "takerFeeRate": "0.0015",
        //         "makerFeeRate": "0"
        //       }
        //     ]
        // }
        const data = this.safeValue(response, 'data', []);
        const result = {};
        for (let i = 0; i < data.length; i++) {
            const taker = this.safeString(response[i], 'takerFeeRate');
            const maker = this.safeString(response[i], 'makerFeeRate');
            const symbol = this.symbol(this.safeString(response[i], 'symbol'));
            result[symbol] = {
                'info': response[i],
                'symbol': symbol,
                'maker': this.parseNumber(maker),
                'taker': this.parseNumber(taker),
                'percentage': true,
                'tierBased': false,
            };
        }
        return result;
    }
    /**
     * @method
     * @name korbit#fetchTradingFee
     * @see https://docs.korbit.co.kr/#REST-get-_v2_tradingFeePolicy
     * @description fetch the trading fees for a market
     * @param {string} symbol unified market symbol
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [fee structure]{@link https://docs.ccxt.com/#/?id=fee-structure}
     */
    async fetchTradingFee(symbol, params = {}) {
        const tradingFee = await this.fetchTradingFee([symbol], params);
        return this.safeValue(tradingFee, symbol);
    }
    parseOHLCV(ohlcv, market = undefined) {
        //
        // {
        //     "timestamp": 1708041600000,
        //     "open": "71211000",
        //     "high": "9999990000",
        //     "low": "300000",
        //     "close": "71392000",
        //     "volume": "1.932320026577213946"
        // }
        //
        return [
            this.safeInteger(ohlcv, 'timestamp'),
            this.safeNumber(ohlcv, 'open'),
            this.safeNumber(ohlcv, 'high'),
            this.safeNumber(ohlcv, 'low'),
            this.safeNumber(ohlcv, 'close'),
            this.safeNumber(ohlcv, 'volume'),
        ];
    }
    /**
     * @method
     * @name korbit#fetchOHLCV
     * @see https://docs.korbit.co.kr/#REST-get-_v2_candles
     * @description fetches historical candlestick data containing the open, high, low, and close price, and the volume of a market
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} timeframe the length of time each candle represents
     * @param {int} [since] timestamp in ms of the earliest candle to fetch
     * @param {int} [limit] the maximum amount of candles to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    async fetchOHLCV(symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const until = this.safeInteger(params, 'until');
        params = this.omit(params, ['until']);
        if (limit === undefined) {
            limit = 200;
        }
        const request = {
            'symbol': market['id'],
            'interval': this.safeString(this.timeframes, timeframe, timeframe),
            'limit': limit,
        };
        if (since !== undefined) {
            request['start'] = since;
        }
        if (until !== undefined) {
            request['end'] = until;
        }
        const response = await this.publicGetCandles(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "timestamp": 1708041600000,
        //         "open": "71211000",
        //         "high": "9999990000",
        //         "low": "300000",
        //         "close": "71392000",
        //         "volume": "1.932320026577213946"
        //       },
        //       {
        //         "timestamp": 1708045200000,
        //         "open": "73510000",
        //         "high": "74605000",
        //         "low": "300000",
        //         "close": "72315000",
        //         "volume": "2.418698679231323743"
        //       },
        //       {
        //         "timestamp": 1708048800000,
        //         "open": "72315000",
        //         "high": "9999990000",
        //         "low": "300000",
        //         "close": "72380000",
        //         "volume": "1.947520219976227299"
        //       },
        //       {
        //         "timestamp": 1708052400000,
        //         "open": "70267000",
        //         "high": "74777000",
        //         "low": "300000",
        //         "close": "74049000",
        //         "volume": "2.254855048982521506"
        //       },
        //       {
        //         "timestamp": 1708056000000,
        //         "open": "68304000",
        //         "high": "74834000",
        //         "low": "68241000",
        //         "close": "74825000",
        //         "volume": "0.630193755379195341"
        //       }
        //     ]
        // }
        //
        return this.parseOHLCVs(response, market, timeframe, since, limit);
    }
    /**
     * @method
     * @name korbit#createOrder
     * @description create a trade order
     * @see https://docs.korbit.co.kr/#REST-post-_v2_orders
     * @param {string} symbol unified symbol of the market to create an order in
     * @param {string} type 'market' or 'limit'
     * @param {string} side 'buy' or 'sell'
     * @param {float} amount how much you want to trade in units of the base currency
     * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {float} [params.cost] for market buy orders, the quote quantity that can be used as an alternative for the amount
     * @param {string} [params.timeInForce] 'IOC' or 'FOK'
     * @param {string} [params.clientOrderId] client order id
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async createOrder(symbol, type, side, amount, price = undefined, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'symbol': market['id'],
            'side': side,
            'orderType': type,
        };
        if (type === 'limit') {
            request['price'] = this.priceToPrecision(symbol, price);
        }
        if ((type === 'market') && (side === 'buy')) {
            // for market buy it requires the amount of quote currency to spend
            let quoteAmount = undefined;
            let createMarketBuyOrderRequiresPrice = true;
            [createMarketBuyOrderRequiresPrice, params] = this.handleOptionAndParams(params, 'createOrder', 'createMarketBuyOrderRequiresPrice', true);
            const cost = this.safeNumber(params, 'cost');
            params = this.omit(params, 'cost');
            if (cost !== undefined) {
                quoteAmount = this.costToPrecision(symbol, cost);
            }
            else if (createMarketBuyOrderRequiresPrice) {
                if (price === undefined) {
                    throw new InvalidOrder(this.id + ' createOrder() requires the price argument for market buy orders to calculate the total cost to spend (amount * price), alternatively set the createMarketBuyOrderRequiresPrice option or param to false and pass the cost to spend (quote quantity) in the amount argument');
                }
                else {
                    const amountString = this.numberToString(amount);
                    const priceString = this.numberToString(price);
                    const costRequest = Precise.stringMul(amountString, priceString);
                    quoteAmount = this.costToPrecision(symbol, costRequest);
                }
            }
            else {
                quoteAmount = this.costToPrecision(symbol, amount);
            }
            request['amt'] = quoteAmount;
        }
        else {
            request['qty'] = this.amountToPrecision(symbol, amount);
        }
        const clientOrderId = this.safeString(params, 'clientOrderId');
        if (clientOrderId !== undefined) {
            request['clientOrderId'] = clientOrderId;
        }
        if (type !== 'market') {
            const timeInForce = this.safeStringLower(params, 'timeInForce');
            params = this.omit(params, 'timeInForce');
            if (timeInForce !== undefined) {
                request['timeInForce'] = timeInForce;
            }
        }
        params = this.omit(params, 'clientOrderId');
        const response = await this.privatePostOrders(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": {
        //       "orderId": 1234
        //     }
        // }
        //
        const data = this.safeValue(response, 'data', {});
        return this.parseOrder(data);
    }
    /**
     * @method
     * @name korbit#cancelOrder
     * @see https://docs.korbit.co.kr/#REST-delete-_v2_orders
     * @description cancels an open order
     * @param {string} id order id
     * @param {string} symbol unified symbol of the market to cancel an order
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.clientOrderId] client order id
     * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async cancelOrder(id = undefined, symbol, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'symbol': market['id'],
        };
        if (id !== undefined) {
            request['orderId'] = id;
        }
        const clientOrderId = this.safeString(params, 'clientOrderId');
        if (clientOrderId !== undefined) {
            request['clientOrderId'] = clientOrderId;
        }
        if (id === undefined && clientOrderId === undefined) {
            throw new BadRequest(this.id + ' cancelOrder() requires id or clientOrderId argument');
        }
        params = this.omit(params, 'clientOrderId');
        await this.privateDeleteOrders(this.extend(request, params));
        //
        // {
        //     "success": true
        // }
        //
        return this.parseOrder(request);
    }
    /**
     * @method
     * @name korbit#fetchDeposits
     * @see https://docs.korbit.co.kr/#REST-get-_v2_coin_recentDeposits
     * @description fetch all deposits made to an account
     * @param {string} code unified currency code
     * @param {int} [since] the earliest time in ms to fetch deposits for
     * @param {int} [limit] the maximum number of deposits structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [transaction structures]{@link https://docs.ccxt.com/#/?id=transaction-structure}
     */
    async fetchDeposits(code = undefined, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        const request = {};
        let currency = undefined;
        if (code !== undefined) {
            currency = this.currency(code);
            request['currency'] = currency['id'];
        }
        if (limit === undefined) {
            limit = 100;
        }
        request['limit'] = limit;
        const response = await this.privateGetCoinRecentDeposits(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "id": 1234,
        //         "network": "BTC",
        //         "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        //         "secondaryAddress": null,
        //         "status": "done",
        //         "transactionHash": "0x000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        //         "currency": "btc",
        //         "quantity": "1.234",
        //         "createdAt": 1700000000000
        //       }
        //     ]
        // }
        //
        const data = this.safeValue(response, 'data', []);
        return this.parseTransactions(data, currency, since, limit);
    }
    /**
     * @method
     * @name korbit#fetchWithdrawals
     * @see https://docs.korbit.com/reference/%EC%A0%84%EC%B2%B4-%EC%B6%9C%EA%B8%88-%EC%A1%B0%ED%9A%8C
     * @description fetch all withdrawals made from an account
     * @param {string} code unified currency code
     * @param {int} [since] the earliest time in ms to fetch withdrawals for
     * @param {int} [limit] the maximum number of withdrawals structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [transaction structures]{@link https://docs.ccxt.com/#/?id=transaction-structure}
     */
    async fetchWithdrawals(code = undefined, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        const request = {};
        let currency = undefined;
        if (code !== undefined) {
            currency = this.currency(code);
            request['currency'] = currency['id'];
        }
        if (limit !== undefined) {
            request['limit'] = limit; // default is 100
        }
        const response = await this.privateGetCoinRecentWithdrawals(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "id": 1234,
        //         "quantity": "1.234",
        //         "fee": "0.0001",
        //         "currency": "btc",
        //         "status": "done",
        //         "network": "BTC",
        //         "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        //         "secondaryAddress": null,
        //         "transactionHash": "0x000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        //         "createdAt": 1700000000000
        //       }
        //     ]
        // }
        //
        const data = this.safeValue(response, 'data', []);
        return this.parseTransactions(data, currency, since, limit);
    }
    parseTransactionStatus(status) {
        const statuses = {
            'pending': 'pending',
            'actionRequired': 'pending',
            'reviewing': 'pending',
            'processing': 'pending',
            'done': 'ok',
            'refunded': 'failed',
            'canceled': 'canceled',
            'failed': 'failed',
        };
        return this.safeString(statuses, status, status);
    }
    parseTransaction(transaction, currency = undefined) {
        //
        // fetchDeposits
        //
        // {
        //     "id": 1234,
        //     "network": "BTC",
        //     "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        //     "secondaryAddress": null,
        //     "status": "done",
        //     "transactionHash": "0x000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        //     "currency": "btc",
        //     "quantity": "1.234",
        //     "createdAt": 1700000000000
        // }
        //
        // fetchWithdrawals
        //
        // {
        //     "id": 1234,
        //     "quantity": "1.234",
        //     "fee": "0.0001",
        //     "currency": "btc",
        //     "status": "done",
        //     "network": "BTC",
        //     "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        //     "secondaryAddress": null,
        //     "transactionHash": "0x000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        //     "createdAt": 1700000000000
        // }
        //
        // withdraw (coin)
        //
        // {
        //     "status": "pending",
        //     "coinWithdrawalId": 1234
        // }
        //
        if (transaction === undefined) {
            return undefined;
        }
        const tag = this.safeString(transaction, 'secondaryAddress');
        const timestamp = this.safeInteger(transaction, 'createdAt');
        const fee = this.safeNumber(transaction, 'fee');
        let type = 'deposit';
        if (fee !== undefined) {
            type = 'withdrawal';
        }
        const currencyId = this.safeString(transaction, 'currency');
        const code = this.safeCurrencyCode(currencyId, currency);
        return {
            'info': transaction,
            'id': this.safeString2(transaction, 'id', 'coinWithdrawalId'),
            'currency': code,
            'amount': this.safeNumber(transaction, 'quantity'),
            'network': this.safeString(transaction, 'network'),
            'address': this.safeString(transaction, 'address'),
            'addressTo': undefined,
            'addressFrom': undefined,
            'tag': tag,
            'tagTo': undefined,
            'tagFrom': undefined,
            'status': this.parseTransactionStatus(this.safeString(transaction, 'status')),
            'type': type,
            'updated': undefined,
            'txid': this.safeString(transaction, 'transactionHash'),
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'internal': undefined,
            'comment': undefined,
            'fee': {
                'currency': code,
                'cost': fee,
            },
        };
    }
    parseOrderStatus(status) {
        const statuses = {
            'pending': 'open',
            'open': 'open',
            'filled': 'closed',
            'canceled': 'canceled',
            'partiallyFilled': 'open',
            'partiallyFilledCanceled': 'canceled',
            'expired': 'canceled',
        };
        return this.safeString(statuses, status, status);
    }
    parseOrder(order, market = undefined) {
        //
        // createOrder
        // {
        //     "orderId": 1234
        // }
        //
        // cancelOrder (manually created in ccxt)
        // {
        //     "symbol": "btc_krw",
        //     "orderId": 1234,
        //     "clientOrderId": "1234-abcd",
        // }
        //
        // fetchOpenOrders
        //
        // {
        //     "orderId": 1234,
        //     "orderType": "limit",
        //     "side": "buy",
        //     "avgPrice": "5000",
        //     "price": "5000",
        //     "qty": "10",
        //     "filledQty": "1",
        //     "filledAmt": "5000",
        //     "createdAt": 1700000000000,
        //     "lastFilledAt": 1700000000000,
        //     "status": "partiallyFilled"
        // }
        //
        // fetchOrder
        //
        // {
        //     "orderId": 1234,
        //     "clientOrderId": "20141231-155959-abcdef",
        //     "symbol": "btc_krw",
        //     "orderType": "limit",
        //     "side": "buy",
        //     "timeInForce": "gtc",
        //     "avgPrice": "5000",
        //     "price": "5000",
        //     "qty": "10",
        //     "filledQty": "1",
        //     "filledAmt": "5000",
        //     "createdAt": 1700000000000,
        //     "lastFilledAt": 1700000000000,
        //     "status": "partiallyFilled"
        // }
        //
        const id = this.safeString(order, 'orderId');
        const clientOrderId = this.safeString(order, 'clientOrderId');
        const marketId = this.safeString(order, 'symbol');
        let type = this.safeString(order, 'orderType');
        const side = this.safeString(order, 'side');
        const timeInForce = this.safeStringUpper(order, 'timeInForce');
        const average = this.safeString(order, 'avgPrice');
        const price = this.safeString(order, 'price');
        const amount = this.safeString(order, 'qty');
        const filled = this.safeString(order, 'filledQty');
        const timestamp = this.safeInteger(order, 'createdAt');
        const lastTradeTimestamp = this.safeInteger(order, 'lastFilledAt');
        const status = this.parseOrderStatus(this.safeString(order, 'status'));
        if (type === 'bbo') {
            type = 'limit';
        }
        market = this.safeMarket(marketId, market);
        return this.safeOrder({
            'info': order,
            'id': id,
            'clientOrderId': clientOrderId,
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'lastTradeTimestamp': lastTradeTimestamp,
            'symbol': market['symbol'],
            'type': type,
            'timeInForce': timeInForce,
            'postOnly': undefined,
            'side': side,
            'price': price,
            'stopPrice': undefined,
            'triggerPrice': undefined,
            'cost': undefined,
            'average': average,
            'amount': amount,
            'filled': filled,
            'remaining': undefined,
            'status': status,
            'fee': undefined,
            'trades': undefined,
        });
    }
    /**
     * @method
     * @name korbit#fetchOpenOrders
     * @description fetch all unfilled currently open orders
     * @see https://docs.korbit.co.kr/#REST-get-_v2_openOrders
     * @param {string} symbol unified market symbol
     * @param {int} [since] the earliest time in ms to fetch open orders for
     * @param {int} [limit] the maximum number of open order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.state] default is 'wait', set to 'watch' for stop limit orders
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async fetchOpenOrders(symbol, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'symbol': market['id'],
        };
        if (limit !== undefined) {
            request['limit'] = limit;
        }
        const response = await this.privateGetOpenOrders(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "orderId": 1234,
        //         "orderType": "limit",
        //         "side": "buy",
        //         "avgPrice": "5000",
        //         "price": "5000",
        //         "qty": "10",
        //         "filledQty": "1",
        //         "filledAmt": "5000",
        //         "createdAt": 1700000000000,
        //         "lastFilledAt": 1700000000000,
        //         "status": "partiallyFilled"
        //       },
        //       {
        //         "orderId": 1235,
        //         "orderType": "limit",
        //         "side": "sell",
        //         "price": "5000",
        //         "qty": "10",
        //         "filledQty": "0",
        //         "filledAmt": "0",
        //         "createdAt": 1700000000000,
        //         "status": "open"
        //       },
        //     ],
        // }
        //
        const data = this.safeValue(response, 'data', []);
        return this.parseOrders(data, market, since, limit);
    }
    /**
     * @method
     * @name korbit#fetchOrder
     * @see https://docs.korbit.co.kr/#REST-get-_v2_orders
     * @description fetches information on an order made by the user
     * @param {string} id order id
     * @param {string} symbol unified market symbol
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async fetchOrder(id = undefined, symbol, params = {}) {
        await this.loadMarkets();
        const market = this.market(symbol);
        const request = {
            'symbol': market['id'],
        };
        if (id !== undefined) {
            request['orderId'] = id;
        }
        const clientOrderId = this.safeString(params, 'clientOrderId');
        if (clientOrderId !== undefined) {
            request['clientOrderId'] = clientOrderId;
        }
        if (id === undefined && clientOrderId === undefined) {
            throw new BadRequest(this.id + ' fetchOrder() requires id or clientOrderId argument');
        }
        params = this.omit(params, 'clientOrderId');
        const response = await this.privateGetOrders(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": {
        //       "orderId": 1234,
        //       "clientOrderId": "20141231-155959-abcdef",
        //       "symbol": "btc_krw",
        //       "orderType": "limit",
        //       "side": "buy",
        //       "timeInForce": "gtc",
        //       "avgPrice": "5000",
        //       "price": "5000",
        //       "qty": "10",
        //       "filledQty": "1",
        //       "filledAmt": "5000",
        //       "createdAt": 1700000000000,
        //       "lastFilledAt": 1700000000000,
        //       "status": "partiallyFilled"
        //     }
        // }
        //
        const data = this.safeValue(response, 'data', {});
        return this.parseOrder(data);
    }
    /**
     * @method
     * @name korbit#fetchDepositAddresses
     * @see https://docs.korbit.co.kr/#REST-get-_v2_coin_depositAddresses
     * @description fetch deposit addresses for multiple currencies and chain types
     * @param {string[]|undefined} codes list of unified currency codes, default is undefined
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a list of [address structures]{@link https://docs.ccxt.com/#/?id=address-structure}
     */
    async fetchDepositAddresses(codes = undefined, params = {}) {
        await this.loadMarkets();
        const response = await this.privateGetCoinDepositAddresses(params);
        //
        // {
        //     "success": true,
        //     "data": [
        //       {
        //         "currency": "btc",
        //         "network": "BTC",
        //         "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
        //       },
        //       {
        //         "currency": "xrp",
        //         "network": "XRP",
        //         "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        //         "secondaryAddress": "1234",
        //       }
        //     ]
        // }
        //
        return this.parseDepositAddresses(response, codes);
    }
    parseDepositAddress(depositAddress, currency = undefined) {
        //
        // {
        //     "currency": "btc",
        //     "network": "BTC",
        //     "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
        // }
        //
        const address = this.safeString(depositAddress, 'address');
        const tag = this.safeString(depositAddress, 'secondaryAddress');
        const currencyId = this.safeString(depositAddress, 'currency');
        const code = this.safeCurrencyCode(currencyId);
        const networkId = this.safeString(depositAddress, 'network');
        this.checkAddress(address);
        return {
            'info': depositAddress,
            'currency': code,
            'network': this.networkIdToCode(networkId),
            'address': address,
            'tag': tag,
        };
    }
    /**
     * @method
     * @name korbit#fetchDepositAddress
     * @see https://docs.korbit.co.kr/#REST-get-_v2_coin_depositAddress
     * @description fetch the deposit address for a currency associated with this account
     * @param {string} code unified currency code
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} params.network deposit chain, can view all chains via this.publicGetWalletAssets, default is eth, unless the currency has a default chain within this.options['networks']
     * @returns {object} an [address structure]{@link https://docs.ccxt.com/#/?id=address-structure}
     */
    async fetchDepositAddress(code, params = {}) {
        await this.loadMarkets();
        const currency = this.currency(code);
        const request = {
            'currency': currency['id'],
        };
        let networkCode = undefined;
        [networkCode, params] = this.handleNetworkCodeAndParams(params);
        if (networkCode !== undefined) {
            request['network'] = this.networkCodeToId(networkCode, currency['code']);
        }
        const response = await this.privateGetCoinDepositAddress(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": {
        //       "currency": "btc",
        //       "network": "BTC",
        //       "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
        //     }
        // }
        //
        const data = this.safeValue(response, 'data', {});
        return this.parseDepositAddress(data);
    }
    /**
     * @method
     * @name korbit#createDepositAddress
     * @see https://docs.korbit.co.kr/#REST-post-_v2_coin_depositAddress
     * @description create a currency deposit address
     * @param {string} code unified currency code of the currency for the deposit address
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an [address structure]{@link https://docs.ccxt.com/#/?id=address-structure}
     */
    async createDepositAddress(code, params = {}) {
        await this.loadMarkets();
        const currency = this.currency(code);
        const request = {
            'currency': currency['id'],
        };
        // https://github.com/ccxt/ccxt/issues/6452
        const response = await this.privatePostCoinDepositAddress(this.extend(request, params));
        //
        // {
        //     "success": true,
        //     "data": {
        //       "currency": "btc",
        //       "network": "BTC",
        //       "address": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
        //     }
        // }
        //
        const data = this.safeValue(response, 'data', {});
        return this.parseDepositAddress(data);
    }
    /**
     * @method
     * @name korbit#withdraw
     * @see https://docs.korbit.co.kr/#REST-post-_v2_coin_withdrawal
     * @see https://docs.korbit.co.kr/#REST-post-_v2_krw_sendKrwWithdrawalPush
     * @description make a withdrawal
     * @param {string} code unified currency code
     * @param {float} amount the amount to withdraw
     * @param {string} address the address to withdraw to
     * @param {string} tag
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [transaction structure]{@link https://docs.ccxt.com/#/?id=transaction-structure}
     */
    async withdraw(code, amount, address, tag = undefined, params = {}) {
        [tag, params] = this.handleWithdrawTagAndParams(tag, params);
        await this.loadMarkets();
        const currency = this.currency(code);
        const request = {
            'amount': amount,
        };
        let response = undefined;
        if (code !== 'KRW') {
            this.checkAddress(address);
            let networkCode = undefined;
            [networkCode, params] = this.handleNetworkCodeAndParams(params);
            if (networkCode !== undefined) {
                request['network'] = this.networkCodeToId(networkCode, currency['code']);
            }
            request['currency'] = currency['id'];
            request['address'] = address;
            if (tag !== undefined) {
                request['secondaryAddress'] = tag;
            }
            response = await this.privatePostCoinWithdrawal(this.extend(request, params));
        }
        else {
            response = await this.privatePostKrwSendKrwWithdrawalPush(this.extend(request, params));
        }
        // Coin
        // {
        //     "success": true,
        //     "data": {
        //       "status": "pending",
        //       "coinWithdrawalId": 1234
        //     }
        // }
        // KRW
        // {"success":true}
        //
        const data = this.safeValue(response, 'data', undefined);
        return this.parseTransaction(data);
    }
    nonce() {
        return this.milliseconds();
    }
    sign(path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        let url = this.implodeParams(this.urls['api'][api], {
            'hostname': this.hostname,
        });
        url += '/' + this.version + '/' + this.implodeParams(path, params);
        const query = this.omit(params, this.extractParams(path));
        if (api === 'private') {
            this.checkRequiredCredentials();
            headers = {};
            query['timestamp'] = this.nonce();
            const signature = this.hmac(this.urlencode(query), this.encode(this.secret), sha256);
            query['signature'] = signature
            headers['X-KAPI-KEY'] = this.apiKey;
            if ((method !== 'GET') && (method !== 'DELETE')) {
                body = this.urlencode(query);
                headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }
        if (method !== 'POST') {
            if (Object.keys(query).length) {
                url += '?' + this.urlencode(query);
            }
        }
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }
    handleErrors(httpCode, reason, url, method, headers, body, response, requestHeaders, requestBody) {
        if (response === undefined) {
            return undefined; // fallback to default error handler
        }
        //
        //   {"success":false,"error":{"code":404,"message":"NOT_FOUND"}}
        //
        const success = this.safeValue(response, 'success');
        const error = this.safeValue(response, 'error');
        if (success !== true) {
            const feedback = this.id + ' ' + body;
            if (error !== undefined) {
                const code = this.safeString(error, 'code');
                const message = this.safeString(error, 'message');
                this.throwExactlyMatchedException(this.exceptions['exact'], code, feedback);
                this.throwExactlyMatchedException(this.exceptions['exact'], message, feedback);
                this.throwBroadlyMatchedException(this.exceptions['broad'], message, feedback);
                this.throwBroadlyMatchedException(this.exceptions['broad'], code, feedback);
            }
            throw new ExchangeError(feedback); // unknown message
        }
        
        return undefined;
    }
}
