// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

//  ---------------------------------------------------------------------------
import korbit from './korbit.js';
//  ---------------------------------------------------------------------------
export default class korbitvip extends korbit {
    describe() {
        return this.deepExtend(super.describe(), {
            'hostname': 'api4.korbit.co.kr',
            'api': {
                'public': {
                    'get': {
                        'tickers': {'cost': 1 / 1000, 'api_rate_limit_group': 'public'},
                        'orderbook': {'cost': 1 / 1000, 'api_rate_limit_group': 'public'},
                        'trades': {'cost': 1 / 1000, 'api_rate_limit_group': 'public'},
                        'candles': {'cost': 1 / 1000, 'api_rate_limit_group': 'public'},
                        'currencyPairs': {'cost': 1 / 1000, 'api_rate_limit_group': 'public'},
                        'currencies': {'cost': 1 / 1000, 'api_rate_limit_group': 'public'},
                        'time': {'cost': 1 / 100, 'api_rate_limit_group': 'public'},
                    },
                },
                'private': {
                    'get': {
                        'orders': {'cost': 1 / 1000, 'api_rate_limit_group': 'orderInfo'},
                        'openOrders': {'cost': 1 / 1000, 'api_rate_limit_group': 'orderInfo'},
                        'allOrders': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'myTrades': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'balance': {'cost': 1 / 1000, 'api_rate_limit_group': 'orderInfo'},
                        'coin/depositAddresses': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'coin/depositAddress': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'coin/recentDeposits': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'coin/deposit': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'coin/withdrawableAddresses': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'coin/withdrawableAmount': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'coin/recentWithdrawals': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'coin/withdrawal': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'krw/recentDeposits': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'krw/recentWithdrawals': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'tradingFeePolicy': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'currentKeyInfo': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                    },
                    'post': {
                        'orders': {'cost': 1 / 60, 'api_rate_limit_group': 'order'},
                        'coin/depositAddress': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'coin/withdrawal': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                        'krw/sendKrwDepositPush': {'cost': 1 / 10, 'api_rate_limit_group': 'krwTransfer'},
                        'krw/sendKrwWithdrawalPush': {'cost': 1 / 10, 'api_rate_limit_group': 'krwTransfer'},
                    },
                    'delete': {
                        'orders': {'cost': 1 / 60, 'api_rate_limit_group': 'orderCancel'},
                        'coin/withdrawal': {'cost': 1 / 100, 'api_rate_limit_group': 'private'},
                    },
                },
            },
            'fees': {
                'trading': {
                    'tierBased': false,
                    'percentage': true,
                    'maker': this.parseNumber('0'),
                    'taker': this.parseNumber('0.0005'),
                },
                'funding': {
                    'tierBased': false,
                    'percentage': false,
                    'withdraw': {},
                    'deposit': {},
                },
            },
        });
    }
}
