// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

//  ---------------------------------------------------------------------------
import korbitvipRest from '../korbitvip.js';
import { ArrayCache, ArrayCacheBySymbolById } from '../base/ws/Cache.js';
import { sha256 } from '../static_dependencies/noble-hashes/sha256.js';
import { jwt } from '../base/functions/rsa.js';
//  ---------------------------------------------------------------------------
export default class korbitvip extends korbitvipRest {
    describe() {
        return this.deepExtend(super.describe(), {
            'has': {
                'ws': true,
                'watchOrderBook': true,
                'watchTicker': true,
                'watchTickers': true,
                'watchTrades': true,
                'watchTradesForSymbols': true,
                'watchOrders': true,
                'watchMyTrades': true,
            },
            'urls': {
                'api': {
                    'ws': 'wss://ws-{hostname}/v2',
                },
            },
            'options': {
                'tradesLimit': 1000,
            },
        });
    }
    /**
     * @method
     * @name korbit#watchTicker
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @see https://docs.korbit.co.kr/#WS-method-subscribe_type-ticker
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
     */
    async watchTicker(symbol, params = {}) {
        return await this.watchPublic(symbol, 'ticker');
    }
    /**
     * @method
     * @name korbit#watchTicker
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @see https://docs.korbit.co.kr/#WS-method-subscribe_type-ticker
     * @param symbols
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
     */
    async watchTickers(symbols = undefined, params = {}) {
        const newTickers = await this.watchPublicMultiple(symbols, 'ticker');
        if (this.newUpdates) {
            const tickers = {};
            tickers[newTickers['symbol']] = newTickers;
            return tickers;
        }
        return this.filterByArray(this.tickers, 'symbol', symbols);
    }
    /**
     * @method
     * @name korbit#watchTrades
     * @description get the list of most recent trades for a particular symbol
     * @see https://docs.korbit.co.kr/#WS-method-subscribe_type-trade
     * @param {string} symbol unified symbol of the market to fetch trades for
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum amount of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=public-trades}
     */
    async watchTrades(symbol, since = undefined, limit = undefined, params = {}) {
        return await this.watchTradesForSymbols([symbol], since, limit, params);
    }
    /**
     * @method
     * @name korbit#watchTradesForSymbols
     * @description get the list of most recent trades for a list of symbols
     * @see https://docs.korbit.co.kr/#WS-method-subscribe_type-trade
     * @param {string[]} symbols unified symbol of the market to fetch trades for
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum amount of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=public-trades}
     */
    async watchTradesForSymbols(symbols, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        symbols = this.marketSymbols(symbols, undefined, false, true, true);
        const channel = 'trade';
        const messageHashes = [];
        const url = this.implodeParams(this.urls['api']['ws'], {
            'hostname': this.hostname,
        });
        if (symbols !== undefined) {
            for (let i = 0; i < symbols.length; i++) {
                const market = this.market(symbols[i]);
                const marketId = market['id'];
                const symbol = market['symbol'];
                this.options[channel] = this.safeValue(this.options, channel, {});
                this.options[channel][symbol] = true;
                messageHashes.push(channel + ':' + marketId);
            }
        }
        const optionSymbols = Object.keys(this.options[channel]);
        const marketIds = this.marketIds(optionSymbols);
        const request = [
            {
                'ticket': this.uuid(),
            },
            {
                'type': channel,
                'codes': marketIds,
                // 'isOnlySnapshot': false,
                // 'isOnlyRealtime': false,
            },
        ];
        const trades = await this.watchPublicMultiple(url, messageHashes, request, messageHashes);
        if (this.newUpdates) {
            const first = this.safeValue(trades, 0);
            const tradeSymbol = this.safeString(first, 'symbol');
            limit = trades.getLimit(tradeSymbol, limit);
        }
        return this.filterBySinceLimit(trades, since, limit, 'timestamp', true);
    }
    /**
     * @method
     * @name korbit#watchOrderBook
     * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://docs.korbit.co.kr/#WS-method-subscribe_type-orderbook
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
     */
    async watchOrderBook(symbol, limit = undefined, params = {}) {
        const orderbook = await this.watchPublic(symbol, 'orderbook');
        return orderbook.limit();
    }
    handleTicker(client, message) {
        // {
        //     "type": "ticker",
        //     "timestamp": 1700000027754,
        //     "symbol": "btc_krw",
        //     "snapshot": true,
        //     "data": {
        //       "open": "94679000",
        //       "high": "111162000",
        //       "low": "93861000",
        //       "close": "99027000",
        //       "prevClose": "94679000",
        //       "priceChange": "4348000",
        //       "priceChangePercent": "4.59",
        //       "volume": "147.94385655",
        //       "quoteVolume": "14311735005.18033",
        //       "bestAskPrice": "99027000",
        //       "bestBidPrice": "99026000",
        //       "lastTradedAt": 1700000010022
        //     }
        // }
        const marketId = this.safeString(message, 'symbol');
        const messageHash = 'ticker:' + marketId;
        const data = this.safeValue(message, 'data', {});
        data['symbol'] = marketId;
        const ticker = this.parseTicker(data);
        const symbol = ticker['symbol'];
        this.tickers[symbol] = ticker;
        client.resolve(ticker, messageHash);
    }
    handleOrderBook(client, message) {
        // {
        //     "type": "orderbook",
        //     "timestamp": 1700000006177,
        //     "symbol": "btc_krw",
        //     "snapshot": true,
        //     "data": {
        //       "timestamp": 1700000000234,
        //       "asks": [
        //         {
        //           "price": "99131000",
        //           "qty": "0.00456677"
        //         },
        //         {
        //           "price": "99132000",
        //           "qty": "0.00616665"
        //         },
        //         {
        //           "price": "99133000",
        //           "qty": "0.00808569"
        //         }
        //       ],
        //       "bids": [
        //         {
        //           "price": "99120000",
        //           "qty": "0.00363422"
        //         },
        //         {
        //           "price": "99119000",
        //           "qty": "0.00475577"
        //         },
        //         {
        //           "price": "99118000",
        //           "qty": "0.00389054"
        //         }
        //       ]
        //     }
        // }
        const marketId = this.safeString(message, 'symbol');
        const symbol = this.safeSymbol(marketId, undefined, '-');
        const isSnapshot = this.safeBool(message, 'snapshot');
        const options = this.safeValue(this.options, 'watchOrderBook', {});
        const limit = this.safeInteger(options, 'limit', 15);
        if (isSnapshot) {
            this.orderbooks[symbol] = this.orderBook({}, limit);
        }
        const orderbook = this.orderbooks[symbol];
        // korbit always returns a snapshot of 15 topmost entries
        // the "REALTIME" deltas are not incremental
        // therefore we reset the orderbook on each update
        // and reinitialize it again with new bidasks
        orderbook.reset({});
        orderbook['symbol'] = symbol;
        const bids = orderbook['bids'];
        const asks = orderbook['asks'];
        const data = this.safeValue(message, 'data', {});
        const dataAsks = this.safeValue(data, 'asks', []);
        const dataBids = this.safeValue(data, 'bids', []);
        for (let i = 0; i < dataAsks.length; i++) {
            const entry = dataAsks[i];
            const price = this.safeFloat(entry, 'price');
            const size = this.safeFloat(entry, 'qty');
            asks.store(price, size);
        }
        for (let i = 0; i < dataBids.length; i++) {
            const entry = dataBids[i];
            const price = this.safeFloat(entry, 'price');
            const size = this.safeFloat(entry, 'qty');
            bids.store(price, size);
        }
        const timestamp = this.safeInteger(data, 'timestamp');
        const datetime = this.iso8601(timestamp);
        orderbook['timestamp'] = timestamp;
        orderbook['datetime'] = datetime;
        const messageHash = 'orderbook:' + marketId;
        client.resolve(orderbook, messageHash);
    }
    handleTrades(client, message) {
        // {
        //     "symbol": "btc_krw",
        //     "timestamp": 1700000005498,
        //     "type": "trade",
        //     "snapshot": true,
        //     "data": [
        //       {
        //         "timestamp": 1700000001239,
        //         "price": "98909000",
        //         "qty": "0.00146702",
        //         "isBuyerTaker": true,
        //         "tradeId": 123456
        //       }
        //     ]
        // }
        const data = this.safeValue(message, 'data', []);
        const marketId = this.safeString(message, 'symbol');
        const timestamp = this.safeInteger(message, 'timestamp');
        for (let i = 0; i < data.length; i++) {
            const entry = data[i];
            entry['symbol'] = marketId;
            entry['timestamp'] = timestamp;
            const trade = this.parseTrade(entry);
            const symbol = trade['symbol'];
            let stored = this.safeValue(this.trades, symbol);
            if (stored === undefined) {
                const limit = this.safeInteger(this.options, 'tradesLimit', 1000);
                stored = new ArrayCache(limit);
                this.trades[symbol] = stored;
            }
            stored.append(trade);
        }
        
        const messageHash = 'trade:' + marketId;
        client.resolve(stored, messageHash);
    }
    async authenticate(params = {}) {
        this.checkRequiredCredentials();
        let url = this.implodeParams(this.urls['api']['ws'], {
            'hostname': this.hostname,
        }) + '/private';
        const wsOptions = this.safeDict(this.options, 'ws', {});
        const authQuery = this.safeString(wsOptions, 'authQuery');
        if (this.clients[url] === undefined || authQuery === undefined) {
            const query = {
                'timestamp': this.nonce(),
            };
            const signature = this.hmac(this.urlencode(query), this.encode(this.secret), sha256);
            query['signature'] = signature;
            const authQuery = '?' + this.urlencode(query);
            wsOptions['authQuery'] = authQuery;
            wsOptions['options'] = {
                'headers': {
                    'X-KAPI-KEY': this.apiKey,
                },
            };
            this.options['ws'] = wsOptions;
            url += authQuery;
        }
        return this.client(url);
    }
    async watchPublic(symbol, channel, messageHash, params = {}) {
        const message = {
            'method': 'subscribe',
            'type': channel,
        };
        if (messageHash === undefined) {
            messageHash = channel;
        };
        if (symbol !== undefined) {
            await this.loadMarkets();
            const market = this.market(symbol);
            symbol = market['symbol'];
            const symbols = [symbol];
            const marketIds = this.marketIds(symbols);
            message['symbols'] = marketIds;
            messageHash = messageHash + ':' + marketIds[0];
        }
        const url = this.implodeParams(this.urls['api']['ws'], {
            'hostname': this.hostname,
        }) + '/public';
        const subscription = {
            'message': message,
        };
        return await this.watch(url, messageHash, [message], messageHash, subscription);
    }
    async watchPublicMultiple(symbols, channel, params = {}) {
        if (symbols === undefined) {
            symbols = this.symbols;
        }
        symbols = this.marketSymbols(symbols);
        const marketIds = this.marketIds(symbols);
        const url = this.implodeParams(this.urls['api']['ws'], {
            'hostname': this.hostname,
        }) + '/public';
        const messageHashes = [];
        for (let i = 0; i < marketIds.length; i++) {
            messageHashes.push(channel + ':' + marketIds[i]);
        }
        const message = {
            'method': 'subscribe',
            'type': channel,
            'symbols': marketIds,
        };
        const subscription = {
            'message': message,
        };
        return await this.watchMultiple(url, messageHashes, [message], messageHashes, subscription);
    }
    async watchPrivate(symbol, channel, messageHash, params = {}) {
        await this.authenticate();
        const message = {
            'method': 'subscribe',
            'type': channel,
        };
        if (messageHash === undefined) {
            messageHash = channel;
        };
        if (symbol !== undefined) {
            await this.loadMarkets();
            const market = this.market(symbol);
            symbol = market['symbol'];
            const symbols = [symbol];
            const marketIds = this.marketIds(symbols);
            message['symbols'] = marketIds;
            messageHash = messageHash + ':' + marketIds[0];
        }
        const wsOptions = this.safeDict(this.options, 'ws', {});
        const authQuery = this.safeString(wsOptions, 'authQuery');
        const url = this.implodeParams(this.urls['api']['ws'], {
            'hostname': this.hostname,
        }) + '/private' + authQuery;
        const subscription = {
            'message': message,
        };
        return await this.watch(url, messageHash, [message], messageHash, subscription);
    }
    async watchPrivateMultiple(symbols, channel, params = {}) {
        await this.authenticate();
        await this.loadMarkets();
        if (symbols === undefined) {
            symbols = this.symbols;
        }
        symbols = this.marketSymbols(symbols);
        const marketIds = this.marketIds(symbols);
        const wsOptions = this.safeDict(this.options, 'ws', {});
        const authQuery = this.safeString(wsOptions, 'authQuery');
        const url = this.implodeParams(this.urls['api']['ws'], {
            'hostname': this.hostname,
        }) + '/private' + authQuery;
        const messageHashes = [];
        for (let i = 0; i < marketIds.length; i++) {
            messageHashes.push(channel + ':' + marketIds[i]);
        }
        const message = {
            'method': 'subscribe',
            'type': channel,
            'symbols': marketIds,
        };
        const subscription = {
            'message': message,
        };
        return await this.watchMultiple(url, messageHashes, [message], messageHashes, subscription);
    }
    /**
     * @method
     * @name korbit#watchOrders
     * @description watches information on multiple orders made by the user
     * @see https://docs.korbit.co.kr/#WS-method-subscribe_type-myOrder
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    async watchOrders(symbol, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        const channel = 'myOrder';
        const messageHash = 'myOrder';
        const orders = await this.watchPrivate(symbol, channel, messageHash);
        if (this.newUpdates) {
            limit = orders.getLimit(symbol, limit);
        }
        return this.filterBySymbolSinceLimit(orders, symbol, since, limit, true);
    }
    /**
     * @method
     * @name korbit#watchMyTrades
     * @description watches information on multiple trades made by the user
     * @see https://docs.korbit.co.kr/#WS-method-subscribe_type-myTrades
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
     */
    async watchMyTrades(symbol, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets();
        const channel = 'myTrade';
        const messageHash = 'myTrade';
        const trades = await this.watchPrivate(symbol, channel, messageHash);
        if (this.newUpdates) {
            limit = trades.getLimit(symbol, limit);
        }
        return this.filterBySymbolSinceLimit(trades, symbol, since, limit, true);
    }
    parseWsOrderStatus(status) {
        const statuses = {
            'wait': 'open',
            'done': 'closed',
            'cancel': 'canceled',
            'watch': 'open',
            'trade': 'open',
        };
        return this.safeString(statuses, status, status);
    }
    parseWsOrder(order, market = undefined) {
        //
        //       {
        //         "orderId": 123456,
        //         "status": "partiallyFilled",
        //         "side": "buy",
        //         "price": "99017000",
        //         "openQty": "0.00206864",
        //         "filledQty": "0.53793136",
        //       }
        //
        const id = this.safeString(order, 'orderId');
        const side = this.safeString(order, 'side');
        const timestamp = this.safeInteger(order, 'timestamp');
        const status = this.parseWsOrderStatus(this.safeString(order, 'status'));
        const marketId = this.safeString(order, 'symbol');
        market = this.safeMarket(marketId, market);
        return this.safeOrder({
            'info': order,
            'id': id,
            'clientOrderId': undefined,
            'timestamp': timestamp,
            'datetime': this.iso8601(timestamp),
            'lastTradeTimestamp': undefined,
            'symbol': market['symbol'],
            'type': undefined,
            'timeInForce': undefined,
            'postOnly': undefined,
            'side': side,
            'price': this.safeString(order, 'price'),
            'stopPrice': undefined,
            'triggerPrice': undefined,
            'cost': undefined,
            'average': undefined,
            'amount': undefined,
            'filled': this.safeString(order, 'filledQty'),
            'remaining': this.safeString(order, 'openQty'),
            'status': status,
            'fee': undefined,
            'trades': undefined,
        });
    }

    handleMyTrade(client, message) {
        // {
        //     "symbol": "btc_krw",
        //     "timestamp": 1700000000000,
        //     "type": "myTrade",
        //     "data": [
        //       {
        //         "tradeId": 123456,
        //         "orderId": 456789,
        //         "side": "buy",
        //         "price": "99051000",
        //         "qty": "0.0013",
        //         "isTaker": true
        //       }
        //     ]
        // }
        let myTrades = this.myTrades;
        if (myTrades === undefined) {
            const limit = this.safeInteger(this.options, 'tradesLimit', 1000);
            myTrades = new ArrayCacheBySymbolById(limit);
        }
        const data = this.safeValue(message, 'data', []);
        const marketId = this.safeString(message, 'symbol');
        const timestamp = this.safeInteger(message, 'timestamp');
        for (let i = 0; i < data.length; i++) {
            const entry = data[i];
            entry['symbol'] = marketId;
            entry['timestamp'] = timestamp;
            const trade = this.parseTrade(entry);
            myTrades.append(trade);
        }
        const messageHash = 'myTrades:' + marketId;
        client.resolve(myTrades, messageHash);
    }
    handleMyOrder(client, message) {
        // {
        //     "symbol": "btc_krw",
        //     "timestamp": 1700000000000,
        //     "type": "myOrder",
        //     "data": [
        //       {
        //         "orderId": 123456,
        //         "status": "partiallyFilled",
        //         "side": "buy",
        //         "price": "99017000",
        //         "openQty": "0.00206864",
        //         "filledQty": "0.53793136",
        //       }
        //     ]
        // }
        const data = this.safeValue(message, 'data', []);
        const marketId = this.safeString(message, 'symbol');
        const timestamp = this.safeInteger(message, 'timestamp');
        for (let i = 0; i < data.length; i++) {
            const entry = data[i];
            entry['symbol'] = marketId;
            entry['timestamp'] = timestamp;
            const parsed = this.parseWsOrder(entry);
            const symbol = this.safeString(parsed, 'symbol');
            const orderId = this.safeString(parsed, 'id');
            if (this.orders === undefined) {
                const limit = this.safeInteger(this.options, 'ordersLimit', 1000);
                this.orders = new ArrayCacheBySymbolById(limit);
            }
            const cachedOrders = this.orders;
            const orders = this.safeValue(cachedOrders.hashmap, symbol, {});
            const order = this.safeValue(orders, orderId);
            if (order !== undefined) {
                const fee = this.safeValue(order, 'fee');
                if (parsed['fee'] === undefined && fee !== undefined) {
                    parsed['fee'] = fee;
                }
                const fees = this.safeValue(order, 'fees');
                if (parsed['fees'] === undefined && fees !== undefined) {
                    parsed['fees'] = fees;
                }
                parsed['trades'] = this.safeValue(order, 'trades');
                parsed['timestamp'] = this.safeInteger(order, 'timestamp');
                parsed['datetime'] = this.safeString(order, 'datetime');
            }
            cachedOrders.append(parsed);
        }
        const messageHash = 'myOrder:' + marketId;
        client.resolve(this.orders, messageHash);
    }
    handleMessage(client, message) {
        const methods = {
            'ticker': this.handleTicker,
            'orderbook': this.handleOrderBook,
            'trade': this.handleTrades,
            'myOrder': this.handleMyOrder,
            'myTrade': this.handleMyTrade,
        };
        const methodName = this.safeString(message, 'type');
        const method = this.safeValue(methods, methodName);
        if (method) {
            method.call(this, client, message);
        }
    }
}
